### ISSUE TITLE
t/sanity.t fails tests 3-18

### ISSUE THREAD

**Issue by coke** [parrot/plumage#2]
I don't see a way to run "prove -v" on the tests, though I was able to run the test file manually with "parrot-nqp t/sanity.t"

I'm on OSX 10.6.5 x86 with gcc 4.2.1

**Comment by fperrad** [comment]
$ prove -v --exec "parrot-nqp" t/sanity.t

$ prove -v -e "parrot-nqp" t/sanity.t 

work fine.

it's a problem with the shebang in t/sanity, with

 #! /usr/local/bin/parrot-nqp

instead of

 #! parrot-nqp

$ prove -v t/sanity.t 

will work, but this shebang depends on configuration/installation of parrot

**Comment by fperrad** [comment]
shebang fixed

**Comment by coke** [comment]
prove -v -e "parrot-nqp" t/sanity.t -- this doesn't actually generate verbose output. (perhaps the test suite never generates the "got" vs. "expected" lines.)

The same tests still fail, after a pulling the latest changes, and "parrot setup.pir clean/build/test" .

Regards.

**Comment by fperrad** [comment]
the verbose option (-v) of prove displays the output of the test, "parrot-nqp t/sanity.t" in this case, and add colors (red for error).

there are no informative message (like, got vs expected),
because tests use the method 'ok', 'nok'.

only methods 'is', 'like' give this kind of information.

**Comment by coke** [comment]
Perhaps this was a parrot-revision mismatch: all tests now passing with

$ parrot_config git_describe
RELEASE_2_11_0-700-g07c6d61

If there's a minimum parrot requirement for plumage, it should probably complain (warn?) during build, rather than blowing up at runtime.
